name: "AI Code Reviewer"
description: "A GitHub Action to review code using AI"
author: "Daniel Belz"
inputs:
  GITHUB_TOKEN:
    description: "GitHub Token for API calls"
    required: false
  OPENAI_API_KEY:
    description: "OpenAI API Key"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI model to use (default: gpt-4)"
    required: false
    default: "gpt-4"
  exclude:
    description: "Files to exclude (e.g., '**/*.json, **/*.md')"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"

