name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - "feature/*" # Replace with the branch pattern you want to trigger on
      - "hotfix/*" # Example: Matches branches like 'feature/my-feature' or 'hotfix/urgent-fix'
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Inputs
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: DanielBelz1997/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-3.5-turbo" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas


