name: PR and Branch Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR creation or updates
  push:
    branches:
      - 'feature/*' # Replace with the branch pattern you want to trigger on
      - 'hotfix/*'  # Example: Matches branches like 'feature/my-feature' or 'hotfix/urgent-fix'

jobs:
  run-workflow:
    name: Run Workflow on PR or Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add steps specific to your workflow
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      # Example step to deploy (use cautiously on push!)
      - name: Deploy (if applicable)
        if: github.event_name == 'push'
        run: echo "Deploying to environment for branch ${{ github.ref_name }}"
